### ISSUE TITLE
How to kill all windows from all workspaces? 

### ISSUE THREAD

**Issue by seriiserii825** [benkaiser/i3-wm-config#2]
Hi, i just start to learn i3wm and when i want to close my notebook, i want to kill all windows from all workspaces, but my shortcut don't work. 

`# Close all windows on all workspaces (any class string)
bindsym $mod+Shift+q [class=”.*”] kill
`

Thanks

**Comment by benkaiser** [comment]
Hey @seriiserii825 this repo isn't really for i3wm support questions. Please direct them to i3 itself or another i3 support forum:
https://github.com/i3/i3/issues
